#!/bin/bash
set -e

export PYTHONPATH="src:$PYTHONPATH"

COMMAND=$1

case "$COMMAND" in
    health)
        python3 -m linux_ops.commands.health
        ;;
    inventory)
        python3 -m linux_ops.commands.inventory
        ;;
    *)
        python3 /home/santiago/linux-ops/main.py
        ;;
esac
